### PR TITLE
Updates for most of F19

### PR DESCRIPTION
**Pull request by daly2**

### CODE REVIEW

**Review by hawkrives — COMMENTED** [review]
Did you… save these with Windows line endings? I'm trying to figure out why Github reports every single line as having changed…

**Review by maxnz — APPROVED** [review]

**Comment by daly2** [comment]
Most of these have changed pretty completely, the whole course is different again. Although a few things are just moved to different homework.

**Review by hawkrives — COMMENTED** [review]
I assume that the professor won’t let you commit the implementation file for the .o files?

**Comment by hawkrives** [comment]
@daly2 Will the professor let you commit the implementation for the `.o` files?

**Comment by daly2** [comment]
Yeah, unfortunately, the professor is not willing to let the source code be committed

**Review by hawkrives — APPROVED** [review]
Apologies for the delay.
Given that this repo exists to help you, the grader, it's not my place to really look at these specs very closely.

**Pull request merged**
